### ISSUE TITLE
Missing f2p_only argument in MypyE93f06ce.get_test_cmd

### ISSUE THREAD

**Issue by MarcCote** [SWE-bench/SWE-smith#99]
With the recent refactoring of the grading logic and RepoProfile (#24), one Python profile, `MypyE93f06ce` has a broken `get_test_cmd` method (see https://github.com/SWE-bench/SWE-smith/blob/main/swesmith/profiles/python.py#L1128).

Step to reproduce:

    python swesmith/harness/eval.py --run_id sanity --predictions_path gold --instance_ids 'python__mypy.e93f06ce.pr_10424'

will produce
```test
Error validating python__mypy.e93f06ce.pr_10424: MypyE93f06ce.get_test_cmd() got an unexpected keyword argument 'f2p_only'
```

**Comment by john-b-yang** [comment]
oh uh oh, yeah i forgot to update the more repo-specific `get_test_cmd`, will do that!

Should be fixed within the next 2 hrs :)

**Comment by MarcCote** [comment]
@john-b-yang there's still an issue.
> Error validating python__mypy.e93f06ce.pr_10424: cannot access local variable 'test_keys' where it is not associated with a value

`test_keys` could be undefined here
https://github.com/SWE-bench/SWE-smith/commit/f3c7f0b1934897706f422698a7a4f5cd052a3610#diff-aaa6d566d40b5c57aa85da5e5e3896719126d5637fbc3b59046562254e12a681R1139

**Comment by john-b-yang** [comment]
Ah darn sorry about that, I should be more careful. Should be an easy fix, will patch soon.

**Comment by MarcCote** [comment]
Almost :D. 
>@john-b-yang get_test_cmd should return a tuple, though.

**Comment by john-b-yang** [comment]
Oh man it was just one of those days 😆
